# Generated by Django 3.1 on 2020-08-16 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Please enter a valid reason', help_text='Please enter a valid reason', max_length=255, verbose_name='reason')),
                ('isMissing', models.BooleanField(default=False)),
                ('todayDate', models.DateField(verbose_name='todayDate')),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.student')),
            ],
        ),
    ]
