# Generated by Django 3.1 on 2020-08-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_auto_20200816_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='reason',
            field=models.CharField(help_text='Tell why the student is missing', max_length=255, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='todayDate',
            field=models.DateField(verbose_name='Date of call'),
        ),
    ]
